services:
  localstack:
    extends:
      file: docker-compose.dev.yml
      service: localstack

  web:
    extends:
      file: docker-compose.dev.yml
      service: web
    # Note: collectstatic runs from inside the docker container and needs
    #       to access localstack through the host machine using host.docker.internal
    #       BUT when we access the django server from our host machine, we need to access
    #       the stored staticfiles via localhost, so export LOCALSTACK_HOST before and after
    command: >
      sh -c "export LOCALSTACK_HOST=host.docker.internal &&
             python tests/manage.py collectstatic --no-input &&
             export PYDEVD_DISABLE_FILE_VALIDATION=1 &&
             export LOCALSTACK_HOST=localhost &&
             python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client tests/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5678:5678" # debugpy
    depends_on:
      - localstack
    environment:
      - LOCALSTACK_HOST=host.docker.internal
