version: "3.9"

services:
  web:
    build: .
    command: python tests/manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-firefox
