version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "$PYTHON_VERSION"
        DJANGO_VERSION: "$DJANGO_VERSION"
        SELENIUM_VERSION: "$SELENIUM_VERSION"
    command: >
      sh -c "python tests/manage.py collectstatic --no-input &&
        python tests/manage.py runserver 0.0.0.0:8000"
    environment:
      - USE_LOCALSTACK=true
    volumes:
      - .:/code
    network_mode: host
    container_name: web_main
