# Generated by Django 3.0.10 on 2020-11-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_auto_20201031_2057"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "ordering": ["shop", "item__name"],
                "verbose_name_plural": "Inventory",
            },
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
