# Generated by Django 3.1.6 on 2021-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_auto_20201108_1717"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="notes",
            field=models.TextField(
                blank=True, default="This is the default", null=True
            ),
        ),
    ]
