# Generated by Django 3.1.6 on 2021-02-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_inventory_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingMall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("shops", models.ManyToManyField(to="market.Shop")),
            ],
        ),
    ]
