# Generated by Django 3.1.6 on 2021-02-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_auto_20210222_0312"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalmanager",
            name="headshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="tmp/gm/headshots"
            ),
        ),
    ]
