# Generated by Django 5.2 on 2026-05-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20220413_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='market.item'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, default='This is the default'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='itemsale',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_sales', to='market.item'),
        ),
        migrations.AlterField(
            model_name='shoppingmall',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_malls', to='market.town'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='market.shop'),
        ),
    ]
