# Generated by Django 5.2 on 2026-05-26 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_generalmanager_email_alter_inventory_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='market.consumer'),
        ),
    ]
