name: Publish Release

on: workflow_dispatch

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  lint:
    uses: ./.github/workflows/lint.yml

  build:
    runs-on: ubuntu-latest
    environment: release
    needs:
      - run-tests
      - lint

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          # Using with <3.13 since cgi was removed in 3.13
          python-version: "3.11"

      - name: Build distribution 📦
        run: |
          pip install -r requirements.txt
          make package

      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: >-
      Publish to PyPI
    if: github.actor == 'trangpham'
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/django-admin-confirm/
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: >-
      Upload to GitHub Release
    needs:
      - publish-to-pypi
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.4.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "$GITHUB_REF_NAME"
          --repo "$GITHUB_REPOSITORY"
          --notes ""
      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the
        # sigstore-produced signatures and certificates.
        run: >-
          gh release upload
          "$GITHUB_REF_NAME" dist/**
          --repo "$GITHUB_REPOSITORY"
