name: Test Release

on: workflow_dispatch

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  lint:
    uses: ./.github/workflows/lint.yml

  build:
    runs-on: ubuntu-latest
    needs:
      - run-tests
      - lint

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          # Using with <3.13 since cgi was removed in 3.13
          python-version: "3.11"

      - name: Build distribution 📦
        run: |
          pip install -r requirements.txt
          make package

      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    if: github.actor == 'trangpham'
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/django-admin-confirm/

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish Python 🐍 distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
