name: Tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [2.2, 3.0]
    env:
      DJANGO_VERSION: ${{ matrix.django-version }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      COMPOSE_INTERACTIVE_NO_CLI: 1
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker for Python 3.6
      if: ${{ matrix.python-version == 3.6 }}
      run: |
        export SELENIUM_VERSION=3.141.0
        docker-compose build
    - name: Build Docker for other Python versions
      if: ${{ matrix.python-version != 3.6 }}
      run: |
        export SELENIUM_VERSION=4.0.0a7
        docker-compose build
    - name: Start Docker
      run: docker-compose up -d
    - name: Integration Test
      run: docker-compose run web make test-all
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true

  coveralls:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
